### ISSUE TITLE
[TASK] Implement Branch Protection Rules for Missing Repositories

### ISSUE THREAD

**Issue by kluge7** [vortexntnu/vortex-ci#24]
### Description of task

We need to establish branch protection rules in repositories that currently lack these settings. Ensuring consistent protection across our repositories will enhance our codebase's security, prevent accidental pushes, and maintain code quality by enforcing pipeline standards.

### Repositories

- [x] perception-auv
- [x] vortex-auv
- [x] vortex-pipeline-detection
- [ ] vortex-stonefish-sim
- [x] vortex-vkf
- [x] vortex-ci
- [x] vortex-msgs
- [x] vortex-aruco-detection
- [x] vortex-blackfly-driver
- [x] vortex-image-filtering
- [x] vortex-auv-embedded
- [x] vortex-asv-embedded
- [x] ros2-unit-tests
- [ ] vortex-deep-learning-pipelines
- [x] isaac_ros_common
- [x] zed-ros2-wrapper
- [ ] vortex-seapath-driver
- [x] vortex-asv
- [x] freya-sitaw
- [ ] vortex-sensor-fusion
- [x] vortex-freya-sim
- [x] vortex-visualization
- [x] stim300-driver
- [x] vortex-m3-sonar-driver
- [x] ouster-lidar-ros2-driver
- [x] freya-automaticFAT
- [x] .github
- [x] office-network-config
- [x] vortex-template-repo
- [x] vortex-dvl-a50

### Specifications

1. **Restrict Direct Pushes to Main/Production Branches.**
- Disable direct push to the main (or equivalent) branch. Only approved pull requests should be allowed to merge into main.
2. **Require Pull Request Reviews**
- Enforce a minimum of 1 or 2 code reviews before any pull request can be merged to main.
3. **Status Checks Requirement**
- Ensure that all required checks (pipelines/tests) are passing before a pull request can be merged.
4. **Prohibit Force Pushing and Rewriting History on Main Branch**
   - Explicitly disable force pushes to the `main` branch to prevent any destructive changes or history rewrites.

### Contacts

@kluge7

**Comment by Hallfred** [comment]
Both office-network-config and vortex-sensor-fusion are private repos, and thus won't be affected by branch protection. I believe these are the only two private repos we currently have.

**Comment by kluge7** [comment]
The leadership team has unanimously agreed to establish a `develop` branch alongside the existing `main` branch. The purpose of the `develop` branch is to serve as an initial staging area where code can be tested before being merged into main. Once code is verified to work as expected in `develop`, it will then be pushed to `main`.

If the `develop` branch is not already set up, please create it by branching from `main`. Additionally, configure branch protection rules for `develop` to ensure it adheres to the same standards as `main`. 👍
